import type { Metadata } from "next";
import { Inter, EB_Garamond, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navigation from "./navigation";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const garamond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-garamond",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="antialiased">
      <body
        className={`${inter.variable} ${garamond.variable} ${robotoMono.variable}`}
      >
        <Providers>
          <div className="mx-auto max-w-3xl py-8 md:py-12 font-sans px-6">
            <Navigation />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
